### ISSUE TITLE
Go: incorrect highlights matching symbols in comments

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-anycode#2] opened 2021-09-28 18:23 UTC
Testing [#2389](https://github.com/microsoft/vscode-internalbacklog/issues/2389)

![image](https://user-images.githubusercontent.com/12758612/135144008-99ff4407-03a7-46ad-9b71-5539c6923f2a.png)

**Comment by jrieken** [comment] 2021-09-29 10:33
@tanhakabir please share the full repo and make sure anycode was activates (check language status item). With my dummy file this is working just fine

<img width="352" alt="Screen Shot 2021-09-29 at 12 32 41" src="https://user-images.githubusercontent.com/1794099/135252275-18d2741a-457d-44a9-86c2-11ac93987c26.png">

**Comment by tanhakabir** [comment] 2021-09-29 16:27
This was the repo: https://github.dev/golang/example

**Comment by jrieken** [comment] 2021-10-01 07:00
<img width="405" alt="Screen Shot 2021-10-01 at 09 00 17" src="https://user-images.githubusercontent.com/1794099/135578796-bf4bd05a-26f8-4893-90c3-77a248a76a4b.png">

Doesn't reproduce with latest anycode and insiders. Closing since I know that you tested on an old version of anycode

**Closed by jrieken** 2021-10-01 07:00 UTC
Labels: needs more info
