### ISSUE TITLE
Anycode does not function on https://github.dev/

### ISSUE THREAD

**Issue by jmarolf** [microsoft/vscode-anycode#22] opened 2022-02-11 21:08 UTC
Extension always crashes with the following output
```log
[Warn  - 1:01:43 PM] no native wasm support detected
[Error - 1:01:43 PM] Server initialization failed.
  Message: Request initialize failed with message: WebAssembly is not defined
  Code: -32603 
[Error - 1:01:43 PM] anycode client: couldn't create connection to server
  Message: Request initialize failed with message: WebAssembly is not defined
  Code: -32603 
```

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4863.0 Safari/537.36 Edg/100.0.1163.0

**Comment by jrieken** [comment] 2022-02-21 10:38
/duplicate of https://github.com/microsoft/vscode/issues/137704

**Closed by jrieken** 2022-02-21 10:38 UTC
